apiVersion: skaffold/v1alpha5
kind: Config
build:
  artifacts:
  - image: medici/publisher
    context: kafka-publisher-service
  - image: medici/subscriber
    context: kafka-subscriber-service
  tagPolicy:
    gitCommit: {}
deploy:
  kubectl:
    manifests:
    - ./kubernetes/publisher-deployment.yaml
    - ./kubernetes/subscriber-deployment.yaml
profiles:
- name: james, dev, kubernetes, kafka
  build:
    local:
      push: false