apiVersion: apps/v1
kind: Deployment
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: publisher
  template:
    metadata:
      labels:
        app: publisher
    spec:
      containers:
      - name: publisher
        image: medici/publisher
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: publisher
  labels:
    app: publisher
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: publisher
  type: NodePort