apiVersion: apps/v1
kind: Deployment
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subscriber
  template:
    metadata:
      labels:
        app: subscriber
    spec:
      containers:
      - name: subscriber
        image: medici/subscriber
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: subscriber
  labels:
    app: subscriber
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: subscriber